name: flutter_prueba_mil
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_database: ^11.3.4
  cloud_firestore: ^5.6.5
  logging: ^1.0.2
  firebase_auth: ^5.5.1
  google_sign_in: ^5.4.3
  flutter_facebook_auth: ^5.0.2
  flutter_signin_button: ^2.0.0
  logger: ^1.0.0
  flutter_native_splash: ^2.2.19

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0


flutter:
  assets:
   - assets/smartphone_logo.png
   - assets/images/
  
  uses-material-design: true

flutter_native_splash:
  color: "#0D47A1" 
  image: assets/images/splash_logo.png 
  android: true
  ios: true
  web: false


